defmodule Flashcards.Repo.Migrations.ScoresAndTests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tests) do
      modify :show_count, :bigint, null: true
      modify :dont_know_count, :bigint, null: true
      modify :know_count, :bigint, null: true
      modify :group_id, :uuid, null: false
      modify :user_id, :uuid
    end

    create index(:tests, [:user_id])

    create index(:tests, [:group_id])
  end

  def down do
    drop_if_exists index(:tests, [:group_id])

    drop_if_exists index(:tests, [:user_id])

    alter table(:tests) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "tests_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :group_id,
             references(:flashcard_groups,
               column: :id,
               name: "tests_group_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: true

      modify :know_count, :bigint, null: false
      modify :dont_know_count, :bigint, null: false
      modify :show_count, :bigint, null: false
    end
  end
end
