defmodule Flashcards.Repo.Migrations.Groups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:flashcards) do
      add :created_by, :uuid, null: false
      add :group_id, :uuid, null: false
    end

    create table(:flashcard_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:flashcards) do
      modify :group_id,
             references(:flashcard_groups,
               column: :id,
               name: "flashcards_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:flashcard_groups) do
      add :name, :text, null: false
      add :created_by, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:flashcard_groups) do
      remove :updated_at
      remove :inserted_at
      remove :created_by
      remove :name
    end

    drop constraint(:flashcards, "flashcards_group_id_fkey")

    alter table(:flashcards) do
      modify :group_id, :uuid
    end

    drop table(:flashcard_groups)

    alter table(:flashcards) do
      remove :group_id
      remove :created_by
    end
  end
end
